#!/usr/bin/env bash

install_packages() {
  sudo apt-get install tmux
  sudo apt-install curl

  git clone https://github.com/vim/vim.git

  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}
